spring:
  application:
    name: eureka-server
eureka:
  server:
      enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
    fetch-registry: false
    register-with-eureka: false
