spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:12000
    sleuth:
      sampler:
      percentage: 1.0
eureka:
  server:
      enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
    fetch-registry: false
    register-with-eureka: false
