server:
  port: 11000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:12000
    sleuth:
      sampler:
        probability: 1