server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
spring:
  application:
    name: zuul-server
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
    goods:
      path: /goods/**
      serviceId: goods-service