spring:
  application:
    name: zuul-server
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: user-server
    api-a:
      path: /goods/**
      serviceId: goods-server